[package]
name = "aoc_common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
eyre = { workspace = true }
tracing = { workspace = true }
color-eyre = { workspace = true }
tracing-subscriber = { workspace = true }
